### ISSUE TITLE
Waline被缩小了

### ISSUE THREAD

**Issue by Cregin** [zchengsite/hexo-theme-oranges#105]
主题是最新版本，hexo是7.0，是什么原因？主题原因嘛？求修复一下，谢谢

![image](https://github.com/zchengsite/hexo-theme-oranges/assets/11453465/6a3beb7a-8408-4b80-8066-e0b17df30191)

**Comment by wangweitung** [comment]
I also have this issue

**Comment by youyou-sudo** [comment]
> 主题是最新版本，hexo是7.0，是什么原因？主题原因嘛？求修复一下，谢谢
> 
> ![image](https://private-user-images.githubusercontent.com/11453465/292559262-6a3beb7a-8408-4b80-8066-e0b17df30191.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjU4ODA3OTcsIm5iZiI6MTcyNTg4MDQ5NywicGF0aCI6Ii8xMTQ1MzQ2NS8yOTI1NTkyNjItNmEzYmViN2EtODQwOC00YjgwLTgwNjYtZTBiMTdkZjMwMTkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTA5VDExMTQ1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc1MWZkMGQ5ZTRjZmNkZDQyMWVhZDcyMmQyN2RhODVmYjNiYmNlNThkM2FlMzZiMzc5YmY4MjE1OWFmNWY4MzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-J_TuNZFTp9F07PqvGcwcmvKyzdxGV_-xNhgqWqhmWQ)

我看了下，V3版本的 Waline CSS `--waline-font-size` 值是 `1rem` 这个属性（使用 `<html>` 的 `font-siza`）；看了下样式表，`html` 的 `font-size` 属性是 `10px`
我设置了样式，顺便加了语言设置，可以看下 PR #115

**Comment by zchengsite** [comment]
#115 已修复，感谢 @youyou-sudo 贡献
