### ISSUE TITLE
文章加密

### ISSUE THREAD

**Issue by Moonerss** [zchengsite/hexo-theme-oranges#11]
尝试使用`hexo-blog-encrypt`对文章进行加密，但是在加密后不能输入密码，是否有解决办法

**Comment by FiftyWu** [comment]
可能orange还没实现

**Comment by Le1a** [comment]
> 可能的范围内实现

我也遇到这个问题了呜呜呜，很难受！

**Comment by zchengsite** [comment]
你好，现已支持hexo-blog-encrypt对文章进行加密，可见[#53](https://github.com/zchengsite/hexo-theme-oranges/pull/53)
使用可见[文档](https://github.com/D0n9X1n/hexo-blog-encrypt/blob/master/ReadMe.zh.md)
