### ISSUE TITLE
线上发布之后的文章时间和本地文档中的修改时间对不上。

### ISSUE THREAD

**Issue by CrazyStudent13** [zchengsite/hexo-theme-oranges#114]
大佬你好。

我的hexo是用gitAction提交之后的环境，自动发布部署的，但是发布之后，我偶然注意到文章时间不对，所有的文章似乎都是那一个时间，我怀疑是哪里有问题。
但是我本地启动了一下，又没有发现问题。

这是线上的
![image](https://github.com/zchengsite/hexo-theme-oranges/assets/30223612/4d705681-8a8a-48b6-8d59-0a92650e92e8)

这是本地的
![image](https://github.com/zchengsite/hexo-theme-oranges/assets/30223612/016c8a9e-8b95-435a-b842-f57c3b3bc009)

我排查了这块代码，没发现什么问题，但是发布之后时间确实不对，可是找不出原因。
还请大佬再运玄功，重开天门（滑稽）
![image](https://github.com/zchengsite/hexo-theme-oranges/assets/30223612/34edcf5e-25bb-4288-a407-4fe1edb1b3eb)

**Comment by hippieZhou** [comment]
我也遇到这个问题，我认为是由于这个地方会从 post.md 里面取 **updated** 字段，但是默认没有，所以你可以把 post.md 里面的新增 **updated** 字段，然后再试试。

**Comment by CrazyStudent13** [comment]
> 我也遇到这个问题，我认为是由于这个地方会从 post.md 里面取 **updated** 字段，但是默认没有，所以你可以把 post.md 里面的新增 **updated** 字段，然后再试试。

感谢，今天晚上试了一下，确认可行。我后续在本地模板里边加上这个字段就好。
