### ISSUE TITLE
膜拜大佬

### ISSUE THREAD

**Issue by baimo2333** [zchengsite/hexo-theme-oranges#12]
我是一个完完全全新人，甚至于昨天才了解hexo.io。因为闲着没事就十分想弄一个个人blog，在bilibili上看了CodeSheep的视频已经成功搭建了，然后就是theme了，你敢信我翻了全部主题，只有两个好看，一个是shoka另一个就是您的oranges！简直太棒了！

**Comment by zchengsite** [comment]
谢谢支持！
