### ISSUE TITLE
如何修改正文部分，超链接文本颜色？

### ISSUE THREAD

**Issue by yanghaowang** [zchengsite/hexo-theme-oranges#16]
我在base.css里面找到如下代码，并加入hover选项来改变链接颜色
![image](https://user-images.githubusercontent.com/1877214/102730738-aeb51d00-4303-11eb-9dfb-30dd86189405.png)
但这部分修改仅对标题或toc内的链接有效，对于正文文本部分的链接没有作用？

**Comment by zchengsite** [comment]
> 我在base.css里面找到如下代码，并加入hover选项来改变链接颜色
> ![image](https://user-images.githubusercontent.com/1877214/102730738-aeb51d00-4303-11eb-9dfb-30dd86189405.png)
> 但这部分修改仅对标题或toc内的链接有效，对于正文文本部分的链接没有作用？

通过浏览器F12控制台检查下对应样式是否被覆盖或造成冲突，如果还有问题可以添加我的联系方式：
QQ：1451426471
微信：oranges__c
QQ邮箱：1451426471@qq.com
备注来意，我会耐心解答

**Comment by yanghaowang** [comment]
Markdown css和base css里面对body里面文本颜色重复定义，因此不便修改……我已经在个人版里修复这个问题，今后只需要在base css里面修改即可。
