### ISSUE TITLE
修改其中theme字段为主题名oranges 这一段是错误的

### ISSUE THREAD

**Issue by by365404** [zchengsite/hexo-theme-oranges#24]
修改其中theme字段为主题名oranges 这一段是错误的

在我的使用过程中只有这样写，才能使用您开发的主题
![QQ截图20201222085724](https://user-images.githubusercontent.com/71537735/102836289-f9ce4d80-4433-11eb-95b4-ffc3818d151f.jpg)

theme: hexo-theme-oranges

**Comment by zchengsite** [comment]
theme字段指定的值是**主题名**（项目下`theme`文件夹中主题文件夹名）
如果修改了主题文件夹名，就需要修改`_config.yml`中theme配置项为修改过后的主题名
比如：本地手动修改主题名`hexo-theme-oranges`为`oranges`后，`_config.yml`配置文件`theme`需修改为修改过后的`oranges`

在主题README中，安装一项是通过`git clone https://github.com/zchengsite/hexo-theme-oranges.git themes/oranges`命令将主题拉取到本地`themes/`文件夹下，并重命名为`oranges`，与单纯的`git clone https://github.com/zchengsite/hexo-theme-oranges.git`是有所区别的。
