### ISSUE TITLE
Dark/Light Mode Added

### ISSUE THREAD

**Issue by yanghaowang** [zchengsite/hexo-theme-oranges#25]
Dark/Light Mode转换功能已经添加……在添加过程中发现，base css和markdown css里面有些不一致的地方需要协调，这样黑白转换后看起来颜色比较和谐统一。

**Comment by zchengsite** [comment]
> Dark/Light Mode转换功能已经添加……在添加过程中发现，base css和markdown css里面有些不一致的地方需要协调，这样黑白转换后看起来颜色比较和谐统一。

已支持！
