### ISSUE TITLE
orange是第一眼就相中的主题！感恩dalao！

### ISSUE THREAD

**Issue by frozenfish123** [zchengsite/hexo-theme-oranges#27]
非计算机专业+hexo小白，很久之前是别人帮忙配置的hexo blog，自己没有打理。近期想在blog上发一些文章，第一眼就看到这个主题，喜欢整体的简洁风，喜欢orange图标的像素格的设计，也喜欢文章标题按时间轴的排列，喜欢目录的横栏设计。总之是一见钟情的主题！特地来感谢大佬的设计~（不知道发在issue里面会不会干扰问问题，但是好像找不到别的合适的地方表达我的感恩之情惹）

**Comment by zchengsite** [comment]
谢谢喜欢！i😜
