### ISSUE TITLE
请求dalao给主页的两边增加一点元素~

### ISSUE THREAD

**Issue by Yihao-Sun** [zchengsite/hexo-theme-oranges#3]
我感觉主页的两边有点空，我在右侧放了一个live2d的图案，希望dalao可以考虑一下给左侧开辟一个区域放些插件，比如日历之类的，我看了一下_partial里面好像没有侧栏的ejs

**Comment by zchengsite** [comment]
你好，感谢反馈！hexo-theme-oranges主题设计出发点就是以极简、干净为主哦。可能是我平时在笔记本上办公的原因，小屏下的主页左右空白其实感觉还好，台式显示屏确实看起来有些空。我考虑了在左右两边加些元素以及放大中间主体内容，但是觉得这样更奇怪了。暂时没有找到针对这个问题的一个好的解决方案。当然如果你有好的想法或者解决方案可以提出来，也欢迎fork贡献你的代码。

**Comment by Yihao-Sun** [comment]
> 你好，感谢反馈！hexo-theme-oranges主题设计出发点就是以极简、干净为主哦。可能是我平时在笔记本上办公的原因，小屏下的主页左右空白其实感觉还好，台式显示屏确实看起来有些空。我考虑了在左右两边加些元素以及放大中间主体内容，但是觉得这样更奇怪了。暂时没有找到针对这个问题的一个好的解决方案。当然如果你有好的想法或者解决方案可以提出来，也欢迎fork贡献你的代码

**Comment by Yihao-Sun** [comment]
好的，确实在笔记本上看起来还好，期待您继续更新To do list上的功能，加油！

**Comment by zchengsite** [comment]
感谢支持与理解！🍻
