### ISSUE TITLE
请问如何上传本地图片呢？

### ISSUE THREAD

**Issue by Rooshy-yang** [zchengsite/hexo-theme-oranges#34]

**Comment by zchengsite** [comment]
> _No description provided._

没理解你的意思，如果要在博客中使用图片
- 把本地图片放在项目资源目录下，如：`images/`目录下，然后相对路径在页面引入即可
- 或者直接使用线上图片地址，图片url引入即可

**Comment by Rooshy-yang** [comment]
把图片放在了/source/images/下,然后在博文中正确引入了相对路径,但是在网站上我看到的确是“the requested content cannot be loaded Please try again later”。请问有什么问题吗？

**Comment by zchengsite** [comment]
> 把图片放在了/source/images/下,然后在博文中正确引入了相对路径,但是在网站上我看到的确是“the requested content cannot be loaded Please try again later”。请问有什么问题吗？

这应该与主题无关，涉及到资源目录问题。
具体可参考[demo](https://hexo.theme.oranges.zcheng.site/images.html)页面
对应仓库代码参考以下：
[资源文件](https://github.com/zchengsite/username.github.io/tree/master/source/images)
[如何使用](https://github.com/zchengsite/username.github.io/edit/master/source/_posts/images.md)
