### ISSUE TITLE
Mathjax数学公式

### ISSUE THREAD

**Issue by Moonerss** [zchengsite/hexo-theme-oranges#4]
作者你好，非常喜欢这个oranges主题，请问现在是否支持mathjax语法输入行内和行间公式，我没有设置成功。

**Comment by zchengsite** [comment]
你好，感谢支持。如果你需要使用[KaTeX](https://katex.org/)或[MathJax](https://www.mathjax.org/)，请参阅[hexo-math](https://github.com/hexojs/hexo-math)官方插件教程进行安装与使用。

请注意：
如果你的hexo 版本 <= 5，请阅读以下内容，否者忽略。
- hexo-math 目前仅支持Hexo 5+版本，请检查你的Hexo版本，确保Hexo版本 >= 5，否者会报错。执行`npm install --save hexo@5.2.0`进行升级。
- hexo升级到5+后，部分配置可能有变动，如在执行命令过程中出现警告或者错误提示，具体参阅[Hexo 5.0.0 Released](https://hexo.io/news/2020/07/29/hexo-5-released/)。
