### ISSUE TITLE
主题如何修改默认配色

### ISSUE THREAD

**Issue by ovuln** [zchengsite/hexo-theme-oranges#42]
我比较喜欢dark，可是没有找到切换默认配色的配置。

**Comment by zchengsite** [comment]
> 我比较喜欢dark，可是没有找到切换默认配色的配置。

- 你好，目前主题配色`light`和`dark`均定义在[主题配置样式文件](https://github.com/zchengsite/hexo-theme-oranges/blob/master/source/css/color-scheme.css)中，目前为写死状态，可自由修改和扩展。
- 后续会考虑暴露为配置项放在配置文件中进行配置。
