### ISSUE TITLE
如何更改某个页面的布局

### ISSUE THREAD

**Issue by hanmmgit** [zchengsite/hexo-theme-oranges#47]
请问如果想要对页面的图标布局进行位置修改，需要在哪里调整。
因为暗色模式和搜索按钮在右下角不太显眼， 想调整一下位置，但找不到是修改哪个文件。

**Comment by zchengsite** [comment]
所有的样式文件都在`/source/css/base.css`中，找到对应对于样式class名即可找到对应位置，[样式目录](https://github.com/zchengsite/hexo-theme-oranges/blob/master/source/css/base.css)
