### ISSUE TITLE
waline评论无法展示

### ISSUE THREAD

**Issue by coderzhw** [zchengsite/hexo-theme-oranges#48]
配置项里面叫serverUrl，comment.ejs里面叫theme.comments.waline.serverURL，没匹配上导致评论无法显示，我本地改了下名字，特意来给你留个言

**Comment by zchengsite** [comment]
好的，感谢指出，稍后会修正

**Comment by zchengsite** [comment]
已修复[#49](https://github.com/zchengsite/hexo-theme-oranges/pull/49)
