### ISSUE TITLE
waline无法评论

### ISSUE THREAD

**Issue by coderzhw** [zchengsite/hexo-theme-oranges#50]
我按照waline文档集成了，但是发现无发评论，貌似是跨域问题还是啥的，有空帮我看看呢，麻烦了，然后发现每次加载文章页面的时候有个null的404请求，不晓得咋回事，我的博客地址是：https://blog.codage.info/
大佬有空帮忙看看咋回事呢

**Comment by zchengsite** [comment]
我没使用过waline评论系统，不熟悉waline配置流程，无法帮到你。
可尝试使用valine评论，主题也默认支持，可参考[valine](https://valine.js.org/quickstart.html)官方文档配置，也可参考[我的hexo demo](https://github.com/zchengsite/zchengsite.github.io)进行配置，有问题再次提问，我可以协助。

**Comment by coderzhw** [comment]
那我去waline的官方github问一下吧，看看咋回事，主要是valine只能部署在leancloud，这一点促使我没用用的欲望了

**Comment by coderzhw** [comment]
已在官方issue解决了此问题
