### ISSUE TITLE
建议添加mac风格的代码块显示

### ISSUE THREAD

**Issue by Le1a** [zchengsite/hexo-theme-oranges#56]
目前的代码块没有mac风格。

希望能添加mac风格的代码块，很多blog主题都有很好看，感觉是个很吸引人的买点。

类似下图。
![image](https://user-images.githubusercontent.com/97610822/162602766-0d79ef8c-e532-42ca-930a-6fc8f7d47124.png)

**Comment by Le1a** [comment]
还有一个需求就是&nbsp; &nbsp;代码块没有一键复制。除了这些 其他的都不是必要的了嘿嘿嘿。很喜欢这种简约的





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月11日(周一) 晚上7:07
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zchengsite/hexo-theme-oranges] 建议添加mac风格的代码块显示 (Issue #56)




 
好的，有时间安排

**Comment by xQmQ** [comment]
如果可以切换代码块风格，我认为这个主题将绝杀。可惜我没这个能力，换不得。期待更新

**Comment by zchengsite** [comment]
现已支持，具体用法见[配置](https://github.com/zchengsite/hexo-theme-oranges/blob/master/_config.yml#L207)，使用中如有问题请提交issue
