### ISSUE TITLE
更新之后使用文章加密会报错

### ISSUE THREAD

**Issue by miraclelll** [zchengsite/hexo-theme-oranges#57]
ERROR TypeError: D:\always\themes\oranges\layout\post.ejs:170
    168|     <% if(theme.comments.enable) { %>
    169|       <div class="comments-container">
 >> 170|         <%- partial("_partial/comments") %>
    171|       </div>
    172|     <% } %>
    173|   </div>

D:\always\themes\oranges\layout\_partial\comments.ejs:1
 >> 1| <% if(theme.comments.enable && theme.comments.waline.enable) { %>
    2|   <script src='//unpkg.com/@waline/client/dist/Waline.min.js'></script>
    3|
    4|   <div id="waline-comments"></div>

Cannot read property 'enable' of undefined
    at eval (D:\always\themes\oranges\layout\_partial\comments.ejs:10:58)
    at comments (D:\always\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiledSync (D:\always\node_modules\hexo\lib\theme\view.js:132:24)
    at _View.renderSync (D:\always\node_modules\hexo\lib\theme\view.js:59:25)
    at Object.partial (D:\always\node_modules\hexo\lib\plugins\helper\partial.js:34:15)
    at eval (D:\always\themes\oranges\layout\post.ejs:229:17)
    at post (D:\always\node_modules\ejs\lib\ejs.js:682:17)
    at _View._compiled (D:\always\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\always\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\always\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\always\node_modules\bluebird\js\release\util.js:16:23)
    at D:\always\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\always\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (internal/streams/readable.js:481:10)
    at resume_ (internal/streams/readable.js:977:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  path: 'D:\\always\\themes\\oranges\\layout\\post.ejs'

**Comment by zchengsite** [comment]
把主题配置文件贴出来看下

**Comment by miraclelll** [comment]
> 把主题配置文件贴出来看下

favicon:
  enable: true
  icon: /images/favicon.png
  touch_icon: /images/favicon.png

# 用户头像与昵称
avatar:
  author_photo: /images/avatar.png
  author_nickname: Miracle-
  path: /

# Google 分析
# https://analytics.google.com
# 注册Google分析账号，在管理/创建媒体资源/选择网站/填写相关信息后得到跟踪Id，一般格式为UA-xxxxxxx-x
# 如之前已有注册账号，在管理/跟踪信息/跟踪代码/找到跟踪ID，一般格式为UA-xxxxxxx-x
gtag:
  enable: false
  gtagkey: UA-xxxxxxx-x

# 文章评论系统
comments:
  enable: true
  # 目前仅支持gitalk, valine, disqus评论，选择喜欢的一种开启即可

  gitalk:
    # https://github.com/gitalk/gitalk#usage查看官方教程
    enable: false
    clientID:
    clientSecret:
    repo:
    owner:
    admin:
    id: location.pathname
    distractionFreeMode: false

  valine:
    # https://valine.js.org/quickstart.html#%E8%8E%B7%E5%8F%96APP-ID-%E5%92%8C-APP-Key
    # 进入以上网址查看官方教程
    enable: true
    appId: LRDflYBpDYwHcKLrQNEsQwoj-gzGzoHsz
    appKey: zmuYPyF7MrRwF3Rv69GDLkV7
    placeholder: Welcome!
    avatar: retro
    vempty_display: false

  # disqus 需科学上网方可使用
  disqus:
    # https://disqus.com/
    # 注册账号，获取shortname.disqus.com，shortname为你定义的唯一name
    # 例：我注册配置完毕后的网址为zxcxxxx.disqus.com，https-zxcxxxx-github-io即为shortname
    enable: false
    shortname: https-zxcxxxx-github-io

# 主题页面导航栏
navbar:
  -
    name: 主页
    enable: true
    path: /
    key: home
  -
    name: 文章
    enable: true
    path: /archives/
    key: archives
  #-
  #  name: 类别
  #  enable: false
  #  path: /categories/
  #  key: categories
  -
    name: 标签
    enable: true
    path: /tags/
    key: tags
  #-
  #  name: 友链
  #  enable: false
  ##  key: friends
  -
    name: 关于
    enable: true
    path: /about/
    key: about

# 文章目录
catalog:
  enable: true

# 文章末尾的上一页与下一页
prevnext:
  enable: true

# 友链详细信息：支持多个友链
friends:
  # nickname: 昵称
  # site: 地址
  # meta: 描述
  -
    nickname: Zcheng
    site: https://zcheng.site/
    meta:
  -
    nickname: Hexo
    site: https://hexo.io/
    meta:

# 页脚信息
footer:
  # social: 社交方式
  # more: 更多页脚信息
  social:
    # name: 名称
    # icon: 图标，目前仅支持IconFont部分图标
    # path: 地址
    -
      name: github
      icon: github
      path: https://github.com/miraclelll
    #-
    #  name: email
    #  icon: envelope
    #  path: peachl@outlook.com
    -
      name: twitter
      icon: twitter
      path:
    #-
    #  name: wechat
    #  icon: wechat
    #  path:
    #-
    #  name: weibo
    #  icon: weibo
    #  path:
    # rss需安装 hexo-generator-feed 插件
    # 具体参照https://github.com/hexojs/hexo-generator-feed
    -
     name: rss
     icon: rss
     path: /atom.xml

  more:
    -
      name: Copyright © Oranges 2020
      path: https://github.com/zchengsite/hexo-theme-oranges
    -
      name: Theme by Oranges | Powered by Hexo
      path: https://github.com/zchengsite/hexo-theme-oranges

# 文章搜索
search:
  enable: true
  placeholder:

# 深/浅配色切换
colorSwitch:
  enable: true

# 文章分享
postShare:
  enable: true

  twitter:
    enable: true

  facebook:
    enable: true

**Comment by miraclelll** [comment]
> 把主题配置文件贴出来看下

**Comment by miraclelll** [comment]
`
# 相关配置说明
  # favicon: 网站图标
  # avatar: 主题用户头像与昵称
  # rss: rss订阅
  # gtag: Google 分析
  # comments: 文章评论系统
    # gitalk
    # disqus
  # navbar: 主题页面导航栏
  # catalog: 文章目录
  # prevnext: 文章末尾的上一页与下一页
  # friends: 友链
  # footer: 页脚信息
  # search: 文章搜索
  # colorSwitch: 深/浅配色切换
  # postShare: 文章分享

# enable: 是否开启相应功能，可选true || false

# 网站图标
favicon:
  enable: true
  icon: /images/favicon.png
  touch_icon: /images/favicon.png

# 用户头像与昵称
avatar:
  author_photo: /images/avatar.png
  author_nickname: Miracle-
  path: /

# Google 分析
# https://analytics.google.com
# 注册Google分析账号，在管理/创建媒体资源/选择网站/填写相关信息后得到跟踪Id，一般格式为UA-xxxxxxx-x
# 如之前已有注册账号，在管理/跟踪信息/跟踪代码/找到跟踪ID，一般格式为UA-xxxxxxx-x
gtag:
  enable: false
  gtagkey: UA-xxxxxxx-x

# 文章评论系统
comments:
  enable: true
  # 目前仅支持gitalk, valine, disqus评论，选择喜欢的一种开启即可

  gitalk:
    # https://github.com/gitalk/gitalk#usage查看官方教程
    enable: false
    clientID:
    clientSecret:
    repo:
    owner:
    admin:
    id: location.pathname
    distractionFreeMode: false

  valine:
    # https://valine.js.org/quickstart.html#%E8%8E%B7%E5%8F%96APP-ID-%E5%92%8C-APP-Key
    # 进入以上网址查看官方教程
    enable: true
    appId: LRDflYBpDYwHcKLrQNEsQwoj-gzGzoHsz
    appKey: zmuYPyF7MrRwF3Rv69GDLkV7
    placeholder: Welcome!
    avatar: retro
    vempty_display: false

  # disqus 需科学上网方可使用
  disqus:
    # https://disqus.com/
    # 注册账号，获取shortname.disqus.com，shortname为你定义的唯一name
    # 例：我注册配置完毕后的网址为zxcxxxx.disqus.com，https-zxcxxxx-github-io即为shortname
    enable: false
    shortname: https-zxcxxxx-github-io

# 主题页面导航栏
navbar:
  -
    name: 主页
    enable: true
    path: /
    key: home
  -
    name: 文章
    enable: true
    path: /archives/
    key: archives
  #-
  #  name: 类别
  #  enable: false
  #  path: /categories/
  #  key: categories
  -
    name: 标签
    enable: true
    path: /tags/
    key: tags
  #-
  #  name: 友链
  #  enable: false
  ##  key: friends
  -
    name: 关于
    enable: true
    path: /about/
    key: about

# 文章目录
catalog:
  enable: true

# 文章末尾的上一页与下一页
prevnext:
  enable: true

# 友链详细信息：支持多个友链
friends:
  # nickname: 昵称
  # site: 地址
  # meta: 描述
  -
    nickname: Zcheng
    site: https://zcheng.site/
    meta:
  -
    nickname: Hexo
    site: https://hexo.io/
    meta:

# 页脚信息
footer:
  # social: 社交方式
  # more: 更多页脚信息
  social:
    # name: 名称
    # icon: 图标，目前仅支持IconFont部分图标
    # path: 地址
    -
      name: github
      icon: github
      path: https://github.com/miraclelll
    #-
    #  name: email
    #  icon: envelope
    #  path: peachl@outlook.com
    -
      name: twitter
      icon: twitter
      path:
    #-
    #  name: wechat
    #  icon: wechat
    #  path:
    #-
    #  name: weibo
    #  icon: weibo
    #  path:
    # rss需安装 hexo-generator-feed 插件
    # 具体参照https://github.com/hexojs/hexo-generator-feed
    -
     name: rss
     icon: rss
     path: /atom.xml

  more:
    -
      name: Copyright © Oranges 2020
      path: https://github.com/zchengsite/hexo-theme-oranges
    -
      name: Theme by Oranges | Powered by Hexo
      path: https://github.com/zchengsite/hexo-theme-oranges

# 文章搜索
search:
  enable: true
  placeholder:

# 深/浅配色切换
colorSwitch:
  enable: true

# 文章分享
postShare:
  enable: true

  twitter:
    enable: true

  facebook:
    enable: true

`

**Comment by zchengsite** [comment]
```yml
# 文章评论系统
comments:
    enable: true
    # 这里缺少waline
```
具体可看https://github.com/zchengsite/hexo-theme-oranges/blob/master/_config.yml#L74

原因是评论配置中缺少了waline，导致逻辑判断waline时出现问题
解决办法：
1、你本地的主题不是最新版本，更新到最新版本，建议通过submodule重新拉取主题，不过先做好差异备份，具体可参考[这里](https://github.com/zchengsite/hexo-theme-oranges/blob/master/README-zh.md#%E5%AE%89%E8%A3%85)

**Comment by miraclelll** [comment]
确实是配置用了旧的，偷懒用旧配置替换了新配置，解决了
