### ISSUE TITLE
国际化不生效

### ISSUE THREAD

**Issue by PeiMouRen** [zchengsite/hexo-theme-oranges#69]
设置语言为中文，页面不生效
hexo配置：
```
language: zh-CN # 
```

页面：
![image](https://user-images.githubusercontent.com/46043280/183397694-190455f5-4eee-43f4-b514-b42f40f0ad68.png)

---
另外，请问有类似于中英文切换的功能吗

**Comment by zchengsite** [comment]
1、导航在主题配置文件中进行配置，见[配置](https://github.com/zchengsite/hexo-theme-oranges/blob/master/_config.yml#L81)
2、动态切换功能暂时没有

**Comment by mikaelzero** [comment]
考虑增加中英文博客切换么
