### ISSUE TITLE
可以出一个 访客人数统计吗？

### ISSUE THREAD

**Issue by Le1a** [zchengsite/hexo-theme-oranges#70]

**Comment by zchengsite** [comment]
近期会加上

**Comment by zchengsite** [comment]
已支持，见[1a6c04a4](https://github.com/zchengsite/hexo-theme-oranges/commit/1a6c04a48d6f33d920cd5bdbe1b4c9f5854ebe6f#diff-ecec67b0e1d7e17a83587c6d27b6baaaa133f42482b07bd3685c77f34b62d883R187)
