### ISSUE TITLE
可以修改默认插图的尺寸吗？目前插入的图片尺寸太小了，看不清字

### ISSUE THREAD

**Issue by Le1a** [zchengsite/hexo-theme-oranges#71]
![image](https://user-images.githubusercontent.com/97610822/184619063-4e895768-15e7-41c5-aa16-9a04165f306e.png)

**Comment by zchengsite** [comment]
这已经是容器承载最大图片尺寸了
- 点击图片可放大
- 适当放大编辑器文本后再截图
