### ISSUE TITLE
关于新版本的一点小问题

### ISSUE THREAD

**Issue by Noicdi** [zchengsite/hexo-theme-oranges#72]
主题色和访客统计两个功能很好，但是主题色支持下的 navbar 和 目录 两个地方的色块位置可能需要调整，且直角矩形可能没有圆角矩形看着舒服。

另，关于 `行间代码` 的字体粗细可以在哪里设置呢？个人感觉粗体比细体的代码看着舒服一些，想要修改一下源码，谢谢

**Comment by zchengsite** [comment]
好的，新版本确实对这几块做了调整，最近会再推出一版，做成可配置项目。😉

**Comment by Noicdi** [comment]
好的👍

**Comment by zchengsite** [comment]
如果需要自行修改，可见[修改记录](https://github.com/zchengsite/hexo-theme-oranges/commit/1a6c04a48d6f33d920cd5bdbe1b4c9f5854ebe6f#diff-5bc92aa7efc919f3bccdcae21fb09162bcbc8537c714956219bc695830e77331L267)

navbar 样式在[L267 - L287](https://github.com/zchengsite/hexo-theme-oranges/commit/1a6c04a48d6f33d920cd5bdbe1b4c9f5854ebe6f#diff-5bc92aa7efc919f3bccdcae21fb09162bcbc8537c714956219bc695830e77331L267)，恢复即可
目录 样式在[L529 - L550](https://github.com/zchengsite/hexo-theme-oranges/commit/1a6c04a48d6f33d920cd5bdbe1b4c9f5854ebe6f#diff-5bc92aa7efc919f3bccdcae21fb09162bcbc8537c714956219bc695830e77331L529)，恢复即可

行间代码粗细样式在[这里](https://github.com/zchengsite/hexo-theme-oranges/commit/1a6c04a48d6f33d920cd5bdbe1b4c9f5854ebe6f#diff-ce657c1076c837c02f06a3bea4909af6a22af105fca9bda5627096aaf797cb27L642)，恢复即可

**Comment by Noicdi** [comment]
好的，谢谢
