### ISSUE TITLE
想问一下navbar的问题

### ISSUE THREAD

**Issue by llllIIIllll** [zchengsite/hexo-theme-oranges#73]
![image](https://user-images.githubusercontent.com/16208288/187496839-0646b3b5-e7b2-451e-80fb-afc37e6d2d41.png)

![image](https://user-images.githubusercontent.com/16208288/187496907-d534f7bb-f30f-47d0-b53c-20cdb3d15b5d.png)

你好，请问一下我这里添加了之后，tag里面直接任何内容都没有了,不知道问题出现在哪里

**Comment by llllIIIlll** [comment]
![image](https://user-images.githubusercontent.com/16208288/187497198-a3e3da36-acc8-4a5f-a9b6-1480c86ca300.png)
![image](https://user-images.githubusercontent.com/16208288/187497228-89ead01a-c7ed-40d7-8bb5-377c104b57a6.png)
我这里如果添加时间的话，会出现两次时间，是和我的hexo和node的版本有影响嘛
![image](https://user-images.githubusercontent.com/16208288/187497469-a0ddaa9e-b1d5-47a2-91c9-16c0552ad818.png)

谢谢了

**Comment by zchengsite** [comment]
> ![image](https://user-images.githubusercontent.com/16208288/187496839-0646b3b5-e7b2-451e-80fb-afc37e6d2d41.png)
> 
> ![image](https://user-images.githubusercontent.com/16208288/187496907-d534f7bb-f30f-47d0-b53c-20cdb3d15b5d.png)
> 
> 你好，请问一下我这里添加了之后，tag里面直接任何内容都没有了,不知道问题出现在哪里


配置是正确的，参考[文档](https://github.com/zchengsite/hexo-theme-oranges/blob/master/README-zh.md#%E9%85%8D%E7%BD%AE)，tag没有出来的原因应该是你其他文章没有指定tag，也就是说可能是你全站文章没有tag来显示，参考hexo文档，[给文章打标签](https://hexo.io/zh-cn/docs/front-matter#%E5%88%86%E7%B1%BB%E5%92%8C%E6%A0%87%E7%AD%BE)

**Comment by llllIIIllll** [comment]
好的，谢谢了
