### ISSUE TITLE
文章页和目录页时间字段错误

### ISSUE THREAD

**Issue by nonPointer** [zchengsite/hexo-theme-oranges#74]
https://github.com/zchengsite/hexo-theme-oranges/blob/1a6c04a48d6f33d920cd5bdbe1b4c9f5854ebe6f/layout/post.ejs#L68-L69
https://github.com/zchengsite/hexo-theme-oranges/blob/1a6c04a48d6f33d920cd5bdbe1b4c9f5854ebe6f/layout/post.ejs#L117-L118

根据 [Hexo 文档](https://hexo.io/docs/variables.html)，`page.date` 代表 post 发表时间，而 `page.updated` 是更新时间。

**Comment by zchengsite** [comment]
好的，已记录，近期会修复，感谢反馈！

**Comment by zchengsite** [comment]
感谢贡献 #94
