### ISSUE TITLE
如何修改使用特定post做主页？

### ISSUE THREAD

**Issue by angushushu** [zchengsite/hexo-theme-oranges#76]
哈罗，很喜欢这个主题。想把主页设成自我介绍的post禁用了home。但是通过域名访问网站时还是会自动到index.ejs，有什么办法让网站打开时自动跳转到某个路径么比如localhost:4000/2022/09/17/test/?
谢谢！

**Comment by zchengsite** [comment]
参考这个进行设置试一下，[链接](https://segmentfault.com/a/1190000039871393)

**Comment by angushushu** [comment]
成功了！太感谢啦！
