### ISSUE TITLE
友链界面无法找到

### ISSUE THREAD

**Issue by edandein** [zchengsite/hexo-theme-oranges#77]
在本地测试一切正常，但是上传到github上就出错了，文件都上传上来了可是就是无法找到，请求指点

**Comment by zchengsite** [comment]
你的[Friends](https://github.com/edandein/edandein.github.io/tree/main/Friends) 文件名是大写，[index.html](https://github.com/edandein/edandein.github.io/blob/main/index.html#L91)a链接引用的是小写。
建议重新生成友链页面 ```hexo new page friends```再试试吧
