### ISSUE TITLE
修改valine输入框样式的方法

### ISSUE THREAD

**Issue by angushushu** [zchengsite/hexo-theme-oranges#78]
哈罗，在用valine做评论但是moren默认的输入窗口很长有点难看。尝试了修改css文件夹里的comments.css和main.css里的valine部分但貌似没有变化。请问有什么其他方法修改valine输入栏的长度么？谢谢！

**Comment by zchengsite** [comment]
修改[comments.css](https://github.com/zchengsite/hexo-theme-oranges/blob/master/source/css/comments.css)里面的样式即可，根据class来对应修改即可，比如修改输入框宽度，新增以下样式即可修改：
```
.comments-container .vcomments .vwrap {
    width: 50%;
}
```
其他的我就不举例了

**Comment by angushushu** [comment]
谢谢回复！尝试修改过comments.css和main.css的样式，但是修改后本地预览没有变化。在chrome的f12里修改没有问题。我是在.comments-container .vwarp里修改了padding。
```
.comments-container .vwrap {
  color: var(--color-text-a);
  padding: 0px !important;
}
```
修改后hexo s清除缓存进入localhost:4000但是没有变化
