### ISSUE TITLE
bash代码高亮

### ISSUE THREAD

**Issue by wonius** [zchengsite/hexo-theme-oranges#8]
编辑代码块时，类型设置为powershell才会有高亮，如果是shell则没有高亮。
麻烦作者帮忙添加下shell高亮的支持，谢谢。

**Comment by zchengsite** [comment]
您好，请使用`bash`关键词，如下：
```shell
# 这是一行注释
sudo apt-get update
```
这样，通过`# 注释`的方式，注释字体颜色看起来更浅。

**Comment by wonius** [comment]
> 编辑代码块时，类型设置为powershell才会有高亮，如果是shell则没有高亮。
> 麻烦作者帮忙添加下shell高亮的支持，谢谢。



> 您好，请使用`bash`关键词，如下：
> 
> ```bash
> # 这是一行注释
> sudo apt-get update
> ```
> 
> ```shell
> # 这是一行注释
> sudo apt-get update
> ```
> 
> 这样，通过`# 注释`的方式，注释字体颜色看起来更浅。

改的话改动比较大😂
问下代码高亮在哪改哇，我看看能不能自己加下支持

**Comment by yanghaowang** [comment]
我也是最近下载这个主题，比较喜欢……

不知道是不是我哪里设置有问题，发现原有.md的post里，代码部分并没有代码框也没有高亮区分。作者有碰到这个问题么？

``` bash
$ hexo new "My New Post"
```

**Comment by zchengsite** [comment]
> 我也是最近下载这个主题，比较喜欢……
> 
> 不知道是不是我哪里设置有问题，发现原有.md的post里，代码部分并没有代码框也没有高亮区分。作者有碰到这个问题么？
> 
> ```shell
> $ hexo new "My New Post"
> ```

你好，贴出代码和在线链接我看看哦

**Comment by yanghaowang** [comment]
> > 我也是最近下载这个主题，比较喜欢……
> > 不知道是不是我哪里设置有问题，发现原有.md的post里，代码部分并没有代码框也没有高亮区分。作者有碰到这个问题么？
> > ```shell
> > $ hexo new "My New Post"
> > ```
> 
> 你好，贴出代码和在线链接我看看哦

我的md文档用notepad打开，代码显示如下

``` bash
$ hexo generate
```

我把这个测试页面直接推到github站点上，可以看这个页面下面就是一些code，但是并没有框，也没有高亮
https://yanghaowang.github.io/posts/20201123_Hello-World-and-Thank-You-Hexo

**Comment by zchengsite** [comment]
> > > 我也是最近下载这个主题，比较喜欢……
> > > 不知道是不是我哪里设置有问题，发现原有.md的post里，代码部分并没有代码框也没有高亮区分。作者有碰到这个问题么？
> > > ```shell
> > > $ hexo new "My New Post"
> > > ```
> > 
> > 
> > 你好，贴出代码和在线链接我看看哦
> 
> 我的md文档用notepad打开，代码显示如下
> 
> ```
> ``` bash (换行)  $ hexo generate (换行) ``` 
> ```
> 
> （edit好多次想打个markdown源码出来，但会被自动编译。。。汗。。。）
> 
> 我把这个测试页面直接推到github站点上，可以看这个页面下面就是一些code
> https://yanghaowang.github.io/posts/20201123_Hello-World-and-Thank-You-Hexo
> 
> 我看到确实是有高亮的区别，但是本身代码框（代码行前面的数字行标）没有显示。

请问您是通过三个反引号```的语法包裹的代码吗？
一般通过这种形式就能编译成`<figure class="highlight">code</figure>`的形式，如下：
![QQ截图20201220130153](https://user-images.githubusercontent.com/34339465/102705497-93c2b880-42c3-11eb-917d-99c217c05296.png)

`class="highlight"` 主题默认样式是：
```css
color: #ccc;
background-color: #2d2d2d;
border-radius: 5px;
```

具体看[demo](https://zcheng.site/hexo-build.html#%E5%AE%89%E8%A3%85node-js)

**Comment by yanghaowang** [comment]
markdown文档里
![image](https://user-images.githubusercontent.com/1877214/102705792-47429300-4259-11eb-943f-2096ab995d55.png)

编译后的网页里
![image](https://user-images.githubusercontent.com/1877214/102705813-92f53c80-4259-11eb-9ecd-83a9ce0f75fe.png)

**Comment by zchengsite** [comment]
检查项目配置文件（非主体配置文件）`_config.yml`下`highlight`配置，确保`enable: true`。
然后
```bash
hexo clean & hexo g
hexo s
```
再次检查是否生效
具体可参考官方[代码高亮](https://hexo.io/zh-cn/docs/syntax-highlight.html)。

**Comment by zchengsite** [comment]
> markdown文档里
> ![image](https://user-images.githubusercontent.com/1877214/102705792-47429300-4259-11eb-943f-2096ab995d55.png)
> 
> 编译后的网页里
> ![image](https://user-images.githubusercontent.com/1877214/102705813-92f53c80-4259-11eb-9ecd-83a9ce0f75fe.png)
> 
> 网页效果
> ![image](https://user-images.githubusercontent.com/1877214/102705826-b9b37300-4259-11eb-9f74-04d45c123690.png)
> 
> 没有代码框，也没有代码行数字行标

检查项目配置文件（非主体配置文件）`_config.yml`下`highlight`配置，确保`enable: true`。
然后
```bash
hexo clean & hexo g
hexo s
```
再次检查是否生效
具体可参考官方[代码高亮](https://hexo.io/zh-cn/docs/syntax-highlight.html)。

**Comment by yanghaowang** [comment]
> > markdown文档里
> > ![image](https://user-images.githubusercontent.com/1877214/102705792-47429300-4259-11eb-943f-2096ab995d55.png)
> > 编译后的网页里
> > ![image](https://user-images.githubusercontent.com/1877214/102705813-92f53c80-4259-11eb-9ecd-83a9ce0f75fe.png)
> > 网页效果
> > ![image](https://user-images.githubusercontent.com/1877214/102705826-b9b37300-4259-11eb-9f74-04d45c123690.png)
> > 没有代码框，也没有代码行数字行标
> 
> 检查项目配置文件（非主题配置文件）`_config.yml`下`highlight`配置，确保`enable: true`。
> 然后
> 
> ```shell
> hexo clean & hexo g
> hexo s
> ```
> 
> 再次检查是否生效
> 具体可参考官方[代码高亮](https://hexo.io/zh-cn/docs/syntax-highlight.html)。

确实是我配置文件里面，highlight沿用之前模板的设置导致了问题，多谢！
