### ISSUE TITLE
C++代碼高亮

### ISSUE THREAD

**Issue by tsengtinghan** [zchengsite/hexo-theme-oranges#83]
你好，想請問如何新增更多語言的highlight，目前的mac-black似乎不支援C++的高亮，而我嘗試在config中新增prismjs但是都無法成功顯示，謝謝!

**Comment by zchengsite** [comment]
你可以使用三个`符号后面加上c++来包裹代码
具体可见[链接](https://coding.net/help/docs/document/wiki/markdown.html#code)
