### ISSUE TITLE
国际版leancloud valine似乎无法评论

### ISSUE THREAD

**Issue by zlx021120** [zchengsite/hexo-theme-oranges#88]
作者你好，我刚刚在我 [博客](https://blog.tanglu.me) 配置了valine但是遇到了这种报错
![image](https://user-images.githubusercontent.com/92848326/225544628-9dd5e8de-da1f-4241-9dd2-ed7ef382fd89.png)

我在valine_issues找到了 [类似的情况](https://github.com/xCss/Valine/issues/340)

但是我看到作者你的博客似乎可以正常评论，所以想请问下我是哪里出错了呀？

我的valine_admin配置如下：

![image](https://user-images.githubusercontent.com/92848326/225547933-6e965380-c70a-41a4-87b1-d11097f6e3a7.png)

![image](https://user-images.githubusercontent.com/92848326/225546093-dcb2d975-0b9c-4546-86b4-aa5fc8226ba0.png)

![image](https://user-images.githubusercontent.com/92848326/225546201-fecacd5b-e8f6-472f-a260-f5e003b6dbf6.png)

**Comment by zchengsite** [comment]
参照这个[解决方案](https://github.com/xCss/Valine/issues/340#issuecomment-698098446)试下

**Comment by tangluya** [comment]
作者你好，我不懂API接口，我照葫芦画瓢 在我hexo配置修改了这两个地方，但更新之后网页都打不开了（我的配置文件是一个月之前的版本）


![image](https://user-images.githubusercontent.com/105842721/226236374-3f9b07e2-627f-40c0-8a73-4b48e54620d0.png)

![image](https://user-images.githubusercontent.com/105842721/226236472-01ffded7-965d-45c2-8bae-e5027b98a265.png)

![image](https://user-images.githubusercontent.com/105842721/226236491-30df2dcc-bb4a-4611-afcb-791c2c00e7be.png)

**Comment by tangluya** [comment]
我博客当前状态为 `layout/_partial/comments.ejs` 文件不变，在 `_config.yml` 文件中添加了"serverURLs: https://你的AppID前8位.api.lncldglobal.com "
可以打开博客 但仍然无法评论

**Comment by zchengsite** [comment]
<%= theme.comments.valine.serverURLs %>
你少了个comments属性
改完后，重新hexo clean && hexo g && hexo s

**Comment by tangluya** [comment]
抱歉，我不是很懂代码。请问是这样修改吗？


    function loadValineSuc() {
      new Valine({
        el: '#vcomments',
        appId: '<%- theme.comments.valine.appId %>',
        appKey: '<%- theme.comments.valine.appKey %>',
        placeholder: '<%- theme.comments.valine.placeholder %>',
        avatar: '<%- theme.comments.valine.avatar %>',
        lang: '<%= config.language %>',

        serverURLs: '<%= theme.valine.serverURLs %>',
        comments: '<%= theme.comments.valine.serverURLs %>'

      })
    }

**Comment by zchengsite** [comment]
```js
function loadValineSuc() {
  new Valine({
    el: '#vcomments',
    appId: '<%- theme.comments.valine.appId %>',
    appKey: '<%- theme.comments.valine.appKey %>',
    placeholder: '<%- theme.comments.valine.placeholder %>',
    avatar: '<%- theme.comments.valine.avatar %>',
    lang: '<%= config.language %>',
    serverURLs: '<%= theme.comments.valine.serverURLs %>'
  })
}
```

**Comment by tangluya** [comment]
感谢大哥，成功了

**Comment by zlx021120** [comment]
[valine使用leancloud国际版 国内无法访问](https://forum.leancloud.cn/t/2022-8/25408)
用了一个月我才发现这个问题，已改用waline 😅

**Comment by zchengsite** [comment]
😅
