### ISSUE TITLE
请教下隐藏"关于我"页面的评论系统

### ISSUE THREAD

**Issue by zlx021120** [zchengsite/hexo-theme-oranges#89]
作者你好，我看您的 [关于](https://hexo.theme.oranges.zcheng.site/about) 页面底部没有评论页面，想请教下是怎么实现的呀

我这两个页面底部也想屏蔽评论 [事件](https://blogtest.tanglu.me/incidents/) [关于我](https://blogtest.tanglu.me/about/)

如果 "事件" 这个页面没有目录就更好了

PS：我 "事件"页面是这样写的，似乎并不规范

![image](https://img.tanglu.me/2023/03/21/w78rzb.webp)

**Comment by zchengsite** [comment]
```
---
title: about
date: 2017-11-04 14:39:03
type: "about"
categories:
tags:
---
```
这俩页面头部加上`type: "about"`，即可按照页面内容来展示。

**Comment by zlx021120** [comment]
soga,感谢
