### ISSUE TITLE
文章页面 <meta> 标记的 description

### ISSUE THREAD

**Issue by nonPointer** [zchengsite/hexo-theme-oranges#92]
建议仿效 [hexo-theme-Anatole](https://github.com/Ben02/hexo-theme-Anatole/wiki/Meta-Description)，手动指定或自动截断前 n 字符正文内容作为文章的描述，便于搜索引擎收录和展示。

**Comment by zchengsite** [comment]
感谢建议，近期安排

**Comment by zchengsite** [comment]
感谢贡献 #93
