### ISSUE TITLE
关于mathjax的问题

### ISSUE THREAD

**Issue by c2h4moe** [zchengsite/hexo-theme-oranges#96]
作者你好，我在typora里输入如下图所示的数学公式在本地可以正常显示，如下图
![typora内部](https://github.com/zchengsite/hexo-theme-oranges/assets/64634941/fd8b00f6-50a0-4ff1-8648-8a77481dd755)
但hexo g&hexo s后在浏览器内无法正常显示（Google Chrome114.0.5735.199）（所用渲染器为 [hexo-renderer-pandoc](https://github.com/hexojs/hexo-renderer-pandoc)）如下图  
![网页上](https://github.com/zchengsite/hexo-theme-oranges/assets/64634941/3ec8cc4e-3c20-4821-869c-47222a142f73)
配置文件_config.yml文件为默认，未改动

个人怀疑问题可能是source\plugins\里**mathjax的版本问题**导致的，理由：从[mathjax](https://github.com/mathjax/MathJax)官网下载最新版（v3.2.2）后用其目录es5文件夹内的tex-chtml.js和input文件夹替换掉原来\source\plugins\mathjax\内部的文件，然后再**hexo clean**&hexo g&hexo s后在浏览器内部就可看到正常效果，如下图
![网页上正常显示](https://github.com/zchengsite/hexo-theme-oranges/assets/64634941/33a357ec-25ea-4336-8f8e-e504f1f7db37)

不太懂技术，如果哪些话说的不专业还请谅解：)

**Comment by zchengsite** [comment]
有可能是[hexo-renderer-pandoc](https://github.com/hexojs/hexo-renderer-pandoc)渲染要求的mathjax插件版本比较高，我没有具体研究过markdown渲染mathjax的细节，如果提升版本能解决问题，也何尝不是一种解决方案。
有关mathjax语法可参考[莱斯大学LaTex Math在线PDF手册](https://www.caam.rice.edu/~heinken/latex/symbols.pdf)，看是否对你有所启发。
🍻

**Comment by c2h4moe** [comment]
感觉应该就是mathjax的版本问题，因为原装的渲染器[hexo-renderer-marked](https://github.com/hexojs/hexo-renderer-marked)这个大括号也渲染不出来。另外其实大部分数学符号渲染都是没有问题的，就是这个分段函数大括号怎么都没法正常显示，很怪:joy:
谢谢回复~
