### ISSUE TITLE
代码高亮语言添加：solidity

### ISSUE THREAD

**Issue by chen4903** [zchengsite/hexo-theme-oranges#97]
solidity属于以太坊编程语言，但也比较小众，orange目前上尚不支持高亮显示markdown代码块标注为solidity的代码，希望增加此语言的代码高亮，谢谢。
例子：https://www.levi104.com/2023/07/28/16.CBSC%20CTF%202022/08.challenge/

**Comment by zchengsite** [comment]
hexo默认使用的代码高亮插件是Highlight.js，好像暂时不支持solidity语言的高亮，你可以选择使用prismjs插件，具体参考：
https://hexo.io/zh-cn/docs/syntax-highlight#Highlight-js
