### ISSUE TITLE
关于字体的问题

### ISSUE THREAD

**Issue by seongnoe** [zchengsite/hexo-theme-oranges#99]
作者您好，感谢您出了如此优美的主题，想请教您关于网站字体样式是在哪里进行修改，现在我想修改网站的字体，我有看到icontfot.css文件夹,也进行了百度查询相关教程。如您能指点一下思路，感激不尽。

**Comment by zchengsite** [comment]
在这里修改，[base.css](https://github.com/zchengsite/hexo-theme-oranges/blob/d26a253957a785ef0d4af6e459798ceb0a746ea0/source/css/base.css#L11)

> 作者您好，感谢您出了如此优美的主题，想请教您关于网站字体样式是在哪里进行修改，现在我想修改网站的字体，我有看到icontfot.css文件夹,也进行了百度查询相关教程。如您能指点一下思路，感激不尽。

**Comment by seongnoe** [comment]
非常感谢！
